export const ManageCommonAbnormality = {
   "library" : {
      "annotation" : [ {
         "translatorOptions" : "",
         "type" : "CqlToElmInfo"
      } ],
      "identifier" : {
         "id" : "ManageCommonAbnormality",
         "version" : "1.1.0"
      },
      "schemaIdentifier" : {
         "id" : "urn:hl7-org:elm",
         "version" : "r1"
      },
      "usings" : {
         "def" : [ {
            "localIdentifier" : "System",
            "uri" : "urn:hl7-org:elm-types:r1"
         }, {
            "localIdentifier" : "FHIR",
            "uri" : "http://hl7.org/fhir",
            "version" : "4.0.1"
         } ]
      },
      "includes" : {
         "def" : [ {
            "localIdentifier" : "FHIRHelpers",
            "path" : "FHIRHelpers",
            "version" : "4.0.1"
         }, {
            "localIdentifier" : "Dash",
            "path" : "DashboardLibrary",
            "version" : "1.0.0"
         }, {
            "localIdentifier" : "Collate",
            "path" : "CollateManagementData",
            "version" : "1.1.0"
         }, {
            "localIdentifier" : "RiskTableLookup",
            "path" : "AutogeneratedTableLookup",
            "version" : "1.0.0"
         } ]
      },
      "contexts" : {
         "def" : [ {
            "name" : "Patient"
         } ]
      },
      "statements" : {
         "def" : [ {
            "name" : "Patient",
            "context" : "Patient",
            "expression" : {
               "type" : "SingletonFrom",
               "operand" : {
                  "dataType" : "{http://hl7.org/fhir}Patient",
                  "templateId" : "http://hl7.org/fhir/StructureDefinition/Patient",
                  "type" : "Retrieve"
               }
            }
         }, {
            "name" : "LookUpTable1",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "name" : "GetGeneralScreeningManagement",
               "libraryName" : "RiskTableLookup",
               "type" : "FunctionRef",
               "operand" : [ {
                  "name" : "SecondMostRecentHpvResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "SecondMostRecentCytologyCotestResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "MostRecentHpvResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "MostRecentCytologyCotestResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               } ]
            }
         }, {
            "name" : "GeneralScreeningManagementRecommendation",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "type" : "If",
               "condition" : {
                  "asType" : "{urn:hl7-org:elm-types:r1}Boolean",
                  "type" : "As",
                  "operand" : {
                     "type" : "Not",
                     "operand" : {
                        "type" : "IsNull",
                        "operand" : {
                           "name" : "LookUpTable1",
                           "type" : "ExpressionRef"
                        }
                     }
                  }
               },
               "then" : {
                  "name" : "LookUpTable1",
                  "type" : "ExpressionRef"
               },
               "else" : {
                  "asType" : "{urn:hl7-org:elm-types:r1}String",
                  "type" : "As",
                  "operand" : {
                     "type" : "Null"
                  }
               }
            }
         }, {
            "name" : "LookUpTable2",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "name" : "GetSurveillanceManagement",
               "libraryName" : "RiskTableLookup",
               "type" : "FunctionRef",
               "operand" : [ {
                  "name" : "ThirdMostRecentHpvResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "ThirdMostRecentCytologyCotestResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "SecondMostRecentHpvResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "SecondMostRecentCytologyCotestResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "MostRecentHpvResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "MostRecentCytologyCotestResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               } ]
            }
         }, {
            "name" : "SurveillanceManagementRecommendation",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "type" : "If",
               "condition" : {
                  "asType" : "{urn:hl7-org:elm-types:r1}Boolean",
                  "type" : "As",
                  "operand" : {
                     "type" : "Not",
                     "operand" : {
                        "type" : "IsNull",
                        "operand" : {
                           "name" : "LookUpTable2",
                           "type" : "ExpressionRef"
                        }
                     }
                  }
               },
               "then" : {
                  "name" : "LookUpTable2",
                  "type" : "ExpressionRef"
               },
               "else" : {
                  "asType" : "{urn:hl7-org:elm-types:r1}String",
                  "type" : "As",
                  "operand" : {
                     "type" : "Null"
                  }
               }
            }
         }, {
            "name" : "LookUpTable3",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "name" : "GetColposcopyResultsManagement",
               "libraryName" : "RiskTableLookup",
               "type" : "FunctionRef",
               "operand" : [ {
                  "name" : "ReferringHpvResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "ReferringCytologyResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "MostRecentBiopsyResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               } ]
            }
         }, {
            "name" : "ColposcopyResultsManagementRecommendation",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "type" : "If",
               "condition" : {
                  "asType" : "{urn:hl7-org:elm-types:r1}Boolean",
                  "type" : "As",
                  "operand" : {
                     "type" : "Not",
                     "operand" : {
                        "type" : "IsNull",
                        "operand" : {
                           "name" : "LookUpTable3",
                           "type" : "ExpressionRef"
                        }
                     }
                  }
               },
               "then" : {
                  "name" : "LookUpTable3",
                  "type" : "ExpressionRef"
               },
               "else" : {
                  "asType" : "{urn:hl7-org:elm-types:r1}String",
                  "type" : "As",
                  "operand" : {
                     "type" : "Null"
                  }
               }
            }
         }, {
            "name" : "LookUpTable4",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "name" : "GetPostColposcopyManagement",
               "libraryName" : "RiskTableLookup",
               "type" : "FunctionRef",
               "operand" : [ {
                  "name" : "ReferringHpvResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "ReferringCytologyResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "MostRecentBiopsyResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "ThirdMostRecentHpvResultPostBiopsy",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "ThirdMostRecentCytologyResultPostBiopsy",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "SecondMostRecentHpvResultPostBiopsy",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "SecondMostRecentCytologyResultPostBiopsy",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "MostRecentHpvResultPostBiopsy",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "MostRecentCytologyResultPostBiopsy",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               } ]
            }
         }, {
            "name" : "PostColposcopyManagementRecommendation",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "type" : "If",
               "condition" : {
                  "asType" : "{urn:hl7-org:elm-types:r1}Boolean",
                  "type" : "As",
                  "operand" : {
                     "type" : "Not",
                     "operand" : {
                        "type" : "IsNull",
                        "operand" : {
                           "name" : "LookUpTable4",
                           "type" : "ExpressionRef"
                        }
                     }
                  }
               },
               "then" : {
                  "name" : "LookUpTable4",
                  "type" : "ExpressionRef"
               },
               "else" : {
                  "asType" : "{urn:hl7-org:elm-types:r1}String",
                  "type" : "As",
                  "operand" : {
                     "type" : "Null"
                  }
               }
            }
         }, {
            "name" : "LookUpTable5",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "name" : "GetPostTreatmentManagement",
               "libraryName" : "RiskTableLookup",
               "type" : "FunctionRef",
               "operand" : [ {
                  "name" : "MostRecentBiopsyResult",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "ThirdMostRecentHpvResultAfterTreatment",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "ThirdMostRecentCytologyResultAfterTreatment",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "SecondMostRecentHpvResultAfterTreatment",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "SecondMostRecentCytologyResultAfterTreatment",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "MostRecentHpvResultAfterTreatment",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "MostRecentCytologyResultAfterTreatment",
                  "libraryName" : "Collate",
                  "type" : "ExpressionRef"
               } ]
            }
         }, {
            "name" : "PostTreatmentManagementRecommendation",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "type" : "If",
               "condition" : {
                  "asType" : "{urn:hl7-org:elm-types:r1}Boolean",
                  "type" : "As",
                  "operand" : {
                     "type" : "Not",
                     "operand" : {
                        "type" : "IsNull",
                        "operand" : {
                           "name" : "LookUpTable5",
                           "type" : "ExpressionRef"
                        }
                     }
                  }
               },
               "then" : {
                  "name" : "LookUpTable5",
                  "type" : "ExpressionRef"
               },
               "else" : {
                  "asType" : "{urn:hl7-org:elm-types:r1}String",
                  "type" : "As",
                  "operand" : {
                     "type" : "Null"
                  }
               }
            }
         }, {
            "name" : "TableRecommendation",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "type" : "Coalesce",
               "operand" : [ {
                  "name" : "PostTreatmentManagementRecommendation",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "PostColposcopyManagementRecommendation",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "ColposcopyResultsManagementRecommendation",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "SurveillanceManagementRecommendation",
                  "type" : "ExpressionRef"
               }, {
                  "name" : "GeneralScreeningManagementRecommendation",
                  "type" : "ExpressionRef"
               } ]
            }
         }, {
            "name" : "WhichTableMadeTheRecommendation",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "type" : "Case",
               "caseItem" : [ {
                  "when" : {
                     "type" : "Not",
                     "operand" : {
                        "type" : "IsNull",
                        "operand" : {
                           "name" : "PostTreatmentManagementRecommendation",
                           "type" : "ExpressionRef"
                        }
                     }
                  },
                  "then" : {
                     "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                     "value" : "5",
                     "type" : "Literal"
                  }
               }, {
                  "when" : {
                     "type" : "Not",
                     "operand" : {
                        "type" : "IsNull",
                        "operand" : {
                           "name" : "PostColposcopyManagementRecommendation",
                           "type" : "ExpressionRef"
                        }
                     }
                  },
                  "then" : {
                     "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                     "value" : "4",
                     "type" : "Literal"
                  }
               }, {
                  "when" : {
                     "type" : "Not",
                     "operand" : {
                        "type" : "IsNull",
                        "operand" : {
                           "name" : "ColposcopyResultsManagementRecommendation",
                           "type" : "ExpressionRef"
                        }
                     }
                  },
                  "then" : {
                     "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                     "value" : "3",
                     "type" : "Literal"
                  }
               }, {
                  "when" : {
                     "type" : "Not",
                     "operand" : {
                        "type" : "IsNull",
                        "operand" : {
                           "name" : "SurveillanceManagementRecommendation",
                           "type" : "ExpressionRef"
                        }
                     }
                  },
                  "then" : {
                     "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                     "value" : "2",
                     "type" : "Literal"
                  }
               }, {
                  "when" : {
                     "type" : "Not",
                     "operand" : {
                        "type" : "IsNull",
                        "operand" : {
                           "name" : "GeneralScreeningManagementRecommendation",
                           "type" : "ExpressionRef"
                        }
                     }
                  },
                  "then" : {
                     "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                     "value" : "1",
                     "type" : "Literal"
                  }
               } ],
               "else" : {
                  "asType" : "{urn:hl7-org:elm-types:r1}Integer",
                  "type" : "As",
                  "operand" : {
                     "type" : "Null"
                  }
               }
            }
         }, {
            "name" : "J1RecommendationText",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "valueType" : "{urn:hl7-org:elm-types:r1}String",
               "value" : "After abnormal cervical cancer screening test results for patients 25 years or older, colposcopic biopsy results, or treatment of histologic HSIL, surveillance with either HPV testing alone or cotesting is preferred (AI). Surveillance with cervical cytology alone is acceptable only if testing with HPV or cotesting is not feasible (CIII). Cytology is recommended at 6-month intervals when 1-year intervals are recommended for HPV or cotesting, and annually when 3-year intervals are recommended for HPV or cotesting (AII).",
               "type" : "Literal"
            }
         }, {
            "name" : "TreatmentWithPregnancyConcernsRecommendationText",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "valueType" : "{urn:hl7-org:elm-types:r1}String",
               "value" : "Endocervical curettage, endometrial biopsy, and treatment without biopsy are unacceptable during pregnancy (EIII). A diagnostic excisional procedure or repeat biopsy is recommended only if cancer is suspected based on cytology, colposcopy, or histology (BII).\n\nFor patients with a diagnosis of histologic HSIL (CIN 2) whose concerns about the effects of treatment on a future pregnancy outweigh their concerns about cancer, either observation or treatment is acceptable provided the squamocolumnar junction is visible and CIN 2+ or ungraded CIN is not identified on endocervical sampling (CII). If the histologic HSIL cannot be specified as CIN 2, treatment is preferred, but observation is acceptable if there are concerns related to future pregnancies (CIII). For patients 25 years or older, observation includes colposcopy and HPV-based testing with cotest or primary hrHPV testing at 6-month intervals for up to 2 years.",
               "type" : "Literal"
            }
         }, {
            "name" : "OneYearSurveillanceRecommendationText",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "valueType" : "{urn:hl7-org:elm-types:r1}String",
               "value" : "When patients have an estimated risk of CIN 3+ based on history and current results that is below the threshold for immediate colposcopy (4.0% immediate risk) and above the 3-year follow-up threshold (≥0.55% at 5 years), repeat testing in 1 year with HPV-based testing is recommended (AII).",
               "type" : "Literal"
            }
         }, {
            "name" : "ThreeYearSurveillanceRecommendationText",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "valueType" : "{urn:hl7-org:elm-types:r1}String",
               "value" : "When patients have an estimated 5-year CIN 3+ risk of 0.15% or greater but less than 0.55% based on history and current test results, repeat testing in 3 years with HPV-based testing is recommended (AII).",
               "type" : "Literal"
            }
         }, {
            "name" : "FiveYearSurveillanceRecommendationText",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "valueType" : "{urn:hl7-org:elm-types:r1}String",
               "value" : "When patients have an estimated 5-year CIN 3+ risk of less than 0.15% based on past history and current test results, return to routine screening at 5-year intervals using HPV-based testing is recommended (AII).",
               "type" : "Literal"
            }
         }, {
            "name" : "ColposcopyRecommendationText",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "valueType" : "{urn:hl7-org:elm-types:r1}String",
               "value" : "For patients 25 years or older, when patients have an estimated immediate risk of diagnosis of CIN 3+ of 4.0% or greater based on history and current results, referral to colposcopy is recommended (AII).\n\nEndocervical curettage, endometrial biopsy, and treatment without biopsy are unacceptable during pregnancy (EIII). A diagnostic excisional procedure or repeat biopsy is recommended only if cancer is suspected based on cytology, colposcopy, or histology (BII).",
               "type" : "Literal"
            }
         }, {
            "name" : "ColposcopyOrTreatmentRecommendationText",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "valueType" : "{urn:hl7-org:elm-types:r1}String",
               "value" : "For nonpregnant patients 25 years or older with an estimated immediate risk of CIN 3+ 25% or greater and less than 60% based on history and current results, treatment using an excisional procedure without previous biopsy confirmation or histologic evaluation with colposcopy and biopsy are both acceptable (AII).",
               "type" : "Literal"
            }
         }, {
            "name" : "TreatmentRecommendationText",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "valueType" : "{urn:hl7-org:elm-types:r1}String",
               "value" : "For nonpregnant patients 25 years or older with an estimated immediate risk of CIN 3+ of 60% or greater based on history and current results, treatment using an excisional procedure without previous biopsy confirmation is preferred but colposcopy with biopsy is acceptable (BII).",
               "type" : "Literal"
            }
         }, {
            "name" : "Over65RecommendationText",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "valueType" : "{urn:hl7-org:elm-types:r1}String",
               "value" : "If patients over age 65 years undergo HPV testing, cotesting, or cytology, management according to guidelines for patients aged 25 to 65 years is recommended (CII). If surveillance testing is recommended for either a history of abnormal screening results or treatment for precancer, discontinuing surveillance is unacceptable if the patient is in reasonably good health and testing is feasible (DII). Discontinuation of surveillance is recommended for patients with a limited life expectancy (EIII). This population will be managed based on logic defined for rare abnormalities and common abnormalities.",
               "type" : "Literal"
            }
         }, {
            "name" : "PositivePrimaryHpv",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "type" : "And",
               "operand" : [ {
                  "type" : "AnyTrue",
                  "source" : {
                     "type" : "Query",
                     "source" : [ {
                        "alias" : "aC",
                        "expression" : {
                           "path" : "allConclusions",
                           "type" : "Property",
                           "source" : {
                              "name" : "MostRecentHpvReport",
                              "libraryName" : "Collate",
                              "type" : "ExpressionRef"
                           }
                        }
                     } ],
                     "relationship" : [ ],
                     "return" : {
                        "expression" : {
                           "type" : "InValueSet",
                           "code" : {
                              "name" : "ToConcept",
                              "libraryName" : "FHIRHelpers",
                              "type" : "FunctionRef",
                              "operand" : [ {
                                 "name" : "aC",
                                 "type" : "AliasRef"
                              } ]
                           },
                           "valueset" : {
                              "name" : "High Risk HPV Positive Results",
                              "libraryName" : "Dash",
                              "type" : "ValueSetRef"
                           }
                        }
                     }
                  }
               }, {
                  "type" : "IsNull",
                  "operand" : {
                     "name" : "MostRecentCytologyCotest",
                     "libraryName" : "Collate",
                     "type" : "ExpressionRef"
                  }
               } ]
            }
         }, {
            "name" : "Recommendation",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "type" : "Case",
               "caseItem" : [ {
                  "when" : {
                     "type" : "And",
                     "operand" : [ {
                        "type" : "And",
                        "operand" : [ {
                           "name" : "PositivePrimaryHpv",
                           "type" : "ExpressionRef"
                        }, {
                           "type" : "Not",
                           "operand" : {
                              "type" : "After",
                              "operand" : [ {
                                 "path" : "date",
                                 "type" : "Property",
                                 "source" : {
                                    "name" : "MostRecentCytologyReport",
                                    "libraryName" : "Collate",
                                    "type" : "ExpressionRef"
                                 }
                              }, {
                                 "path" : "date",
                                 "type" : "Property",
                                 "source" : {
                                    "name" : "MostRecentHpvReport",
                                    "libraryName" : "Collate",
                                    "type" : "ExpressionRef"
                                 }
                              } ]
                           }
                        } ]
                     }, {
                        "type" : "Not",
                        "operand" : {
                           "type" : "After",
                           "operand" : [ {
                              "path" : "date",
                              "type" : "Property",
                              "source" : {
                                 "name" : "MostRecentBiopsyReport",
                                 "libraryName" : "Collate",
                                 "type" : "ExpressionRef"
                              }
                           }, {
                              "path" : "date",
                              "type" : "Property",
                              "source" : {
                                 "name" : "MostRecentHpvReport",
                                 "libraryName" : "Collate",
                                 "type" : "ExpressionRef"
                              }
                           } ]
                        }
                     } ]
                  },
                  "then" : {
                     "type" : "Tuple",
                     "element" : [ {
                        "name" : "action",
                        "value" : {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "",
                           "type" : "Literal"
                        }
                     }, {
                        "name" : "text",
                        "value" : {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "Per the ASCCP Risk Management Guidelines (Egemen et al.), reflex testing with cervical cytology is indicated as surveillance given the patient’s history of abnormal results in order to provide an evidence-based care recommendation.",
                           "type" : "Literal"
                        }
                     } ]
                  }
               }, {
                  "when" : {
                     "type" : "And",
                     "operand" : [ {
                        "type" : "And",
                        "operand" : [ {
                           "type" : "GreaterOrEqual",
                           "operand" : [ {
                              "precision" : "Year",
                              "type" : "CalculateAge",
                              "operand" : {
                                 "path" : "birthDate.value",
                                 "type" : "Property",
                                 "source" : {
                                    "name" : "Patient",
                                    "type" : "ExpressionRef"
                                 }
                              }
                           }, {
                              "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                              "value" : "25",
                              "type" : "Literal"
                           } ]
                        }, {
                           "type" : "LessOrEqual",
                           "operand" : [ {
                              "precision" : "Year",
                              "type" : "CalculateAge",
                              "operand" : {
                                 "path" : "birthDate.value",
                                 "type" : "Property",
                                 "source" : {
                                    "name" : "Patient",
                                    "type" : "ExpressionRef"
                                 }
                              }
                           }, {
                              "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                              "value" : "65",
                              "type" : "Literal"
                           } ]
                        } ]
                     }, {
                        "type" : "Equal",
                        "operand" : [ {
                           "name" : "TableRecommendation",
                           "type" : "ExpressionRef"
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "1-year follow-up",
                           "type" : "Literal"
                        } ]
                     } ]
                  },
                  "then" : {
                     "type" : "Tuple",
                     "element" : [ {
                        "name" : "action",
                        "value" : {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "Surveillance",
                           "type" : "Literal"
                        }
                     }, {
                        "name" : "text",
                        "value" : {
                           "type" : "Concatenate",
                           "operand" : [ {
                              "type" : "Concatenate",
                              "operand" : [ {
                                 "name" : "OneYearSurveillanceRecommendationText",
                                 "type" : "ExpressionRef"
                              }, {
                                 "valueType" : "{urn:hl7-org:elm-types:r1}String",
                                 "value" : "\n\n",
                                 "type" : "Literal"
                              } ]
                           }, {
                              "name" : "J1RecommendationText",
                              "type" : "ExpressionRef"
                           } ]
                        }
                     } ]
                  }
               }, {
                  "when" : {
                     "type" : "And",
                     "operand" : [ {
                        "type" : "Greater",
                        "operand" : [ {
                           "precision" : "Year",
                           "type" : "CalculateAge",
                           "operand" : {
                              "path" : "birthDate.value",
                              "type" : "Property",
                              "source" : {
                                 "name" : "Patient",
                                 "type" : "ExpressionRef"
                              }
                           }
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                           "value" : "65",
                           "type" : "Literal"
                        } ]
                     }, {
                        "type" : "Equal",
                        "operand" : [ {
                           "name" : "TableRecommendation",
                           "type" : "ExpressionRef"
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "1-year follow-up",
                           "type" : "Literal"
                        } ]
                     } ]
                  },
                  "then" : {
                     "type" : "Tuple",
                     "element" : [ {
                        "name" : "action",
                        "value" : {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "Surveillance",
                           "type" : "Literal"
                        }
                     }, {
                        "name" : "text",
                        "value" : {
                           "type" : "Concatenate",
                           "operand" : [ {
                              "type" : "Concatenate",
                              "operand" : [ {
                                 "type" : "Concatenate",
                                 "operand" : [ {
                                    "type" : "Concatenate",
                                    "operand" : [ {
                                       "name" : "OneYearSurveillanceRecommendationText",
                                       "type" : "ExpressionRef"
                                    }, {
                                       "valueType" : "{urn:hl7-org:elm-types:r1}String",
                                       "value" : "\n\n",
                                       "type" : "Literal"
                                    } ]
                                 }, {
                                    "name" : "J1RecommendationText",
                                    "type" : "ExpressionRef"
                                 } ]
                              }, {
                                 "valueType" : "{urn:hl7-org:elm-types:r1}String",
                                 "value" : "\n\n",
                                 "type" : "Literal"
                              } ]
                           }, {
                              "name" : "Over65RecommendationText",
                              "type" : "ExpressionRef"
                           } ]
                        }
                     } ]
                  }
               }, {
                  "when" : {
                     "type" : "And",
                     "operand" : [ {
                        "type" : "And",
                        "operand" : [ {
                           "type" : "GreaterOrEqual",
                           "operand" : [ {
                              "precision" : "Year",
                              "type" : "CalculateAge",
                              "operand" : {
                                 "path" : "birthDate.value",
                                 "type" : "Property",
                                 "source" : {
                                    "name" : "Patient",
                                    "type" : "ExpressionRef"
                                 }
                              }
                           }, {
                              "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                              "value" : "25",
                              "type" : "Literal"
                           } ]
                        }, {
                           "type" : "LessOrEqual",
                           "operand" : [ {
                              "precision" : "Year",
                              "type" : "CalculateAge",
                              "operand" : {
                                 "path" : "birthDate.value",
                                 "type" : "Property",
                                 "source" : {
                                    "name" : "Patient",
                                    "type" : "ExpressionRef"
                                 }
                              }
                           }, {
                              "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                              "value" : "65",
                              "type" : "Literal"
                           } ]
                        } ]
                     }, {
                        "type" : "Equal",
                        "operand" : [ {
                           "name" : "TableRecommendation",
                           "type" : "ExpressionRef"
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "3-year follow-up",
                           "type" : "Literal"
                        } ]
                     } ]
                  },
                  "then" : {
                     "type" : "Tuple",
                     "element" : [ {
                        "name" : "action",
                        "value" : {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "Surveillance",
                           "type" : "Literal"
                        }
                     }, {
                        "name" : "text",
                        "value" : {
                           "type" : "Concatenate",
                           "operand" : [ {
                              "type" : "Concatenate",
                              "operand" : [ {
                                 "name" : "ThreeYearSurveillanceRecommendationText",
                                 "type" : "ExpressionRef"
                              }, {
                                 "valueType" : "{urn:hl7-org:elm-types:r1}String",
                                 "value" : "\n\n",
                                 "type" : "Literal"
                              } ]
                           }, {
                              "name" : "J1RecommendationText",
                              "type" : "ExpressionRef"
                           } ]
                        }
                     } ]
                  }
               }, {
                  "when" : {
                     "type" : "And",
                     "operand" : [ {
                        "type" : "Greater",
                        "operand" : [ {
                           "precision" : "Year",
                           "type" : "CalculateAge",
                           "operand" : {
                              "path" : "birthDate.value",
                              "type" : "Property",
                              "source" : {
                                 "name" : "Patient",
                                 "type" : "ExpressionRef"
                              }
                           }
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                           "value" : "65",
                           "type" : "Literal"
                        } ]
                     }, {
                        "type" : "Equal",
                        "operand" : [ {
                           "name" : "TableRecommendation",
                           "type" : "ExpressionRef"
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "3-year follow-up",
                           "type" : "Literal"
                        } ]
                     } ]
                  },
                  "then" : {
                     "type" : "Tuple",
                     "element" : [ {
                        "name" : "action",
                        "value" : {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "Surveillance",
                           "type" : "Literal"
                        }
                     }, {
                        "name" : "text",
                        "value" : {
                           "type" : "Concatenate",
                           "operand" : [ {
                              "type" : "Concatenate",
                              "operand" : [ {
                                 "type" : "Concatenate",
                                 "operand" : [ {
                                    "type" : "Concatenate",
                                    "operand" : [ {
                                       "name" : "ThreeYearSurveillanceRecommendationText",
                                       "type" : "ExpressionRef"
                                    }, {
                                       "valueType" : "{urn:hl7-org:elm-types:r1}String",
                                       "value" : "\n\n",
                                       "type" : "Literal"
                                    } ]
                                 }, {
                                    "name" : "J1RecommendationText",
                                    "type" : "ExpressionRef"
                                 } ]
                              }, {
                                 "valueType" : "{urn:hl7-org:elm-types:r1}String",
                                 "value" : "\n\n",
                                 "type" : "Literal"
                              } ]
                           }, {
                              "name" : "Over65RecommendationText",
                              "type" : "ExpressionRef"
                           } ]
                        }
                     } ]
                  }
               }, {
                  "when" : {
                     "type" : "And",
                     "operand" : [ {
                        "type" : "And",
                        "operand" : [ {
                           "type" : "GreaterOrEqual",
                           "operand" : [ {
                              "precision" : "Year",
                              "type" : "CalculateAge",
                              "operand" : {
                                 "path" : "birthDate.value",
                                 "type" : "Property",
                                 "source" : {
                                    "name" : "Patient",
                                    "type" : "ExpressionRef"
                                 }
                              }
                           }, {
                              "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                              "value" : "25",
                              "type" : "Literal"
                           } ]
                        }, {
                           "type" : "LessOrEqual",
                           "operand" : [ {
                              "precision" : "Year",
                              "type" : "CalculateAge",
                              "operand" : {
                                 "path" : "birthDate.value",
                                 "type" : "Property",
                                 "source" : {
                                    "name" : "Patient",
                                    "type" : "ExpressionRef"
                                 }
                              }
                           }, {
                              "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                              "value" : "65",
                              "type" : "Literal"
                           } ]
                        } ]
                     }, {
                        "type" : "Equal",
                        "operand" : [ {
                           "name" : "TableRecommendation",
                           "type" : "ExpressionRef"
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "5-year follow-up",
                           "type" : "Literal"
                        } ]
                     } ]
                  },
                  "then" : {
                     "type" : "Tuple",
                     "element" : [ {
                        "name" : "action",
                        "value" : {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "Surveillance",
                           "type" : "Literal"
                        }
                     }, {
                        "name" : "text",
                        "value" : {
                           "type" : "Concatenate",
                           "operand" : [ {
                              "type" : "Concatenate",
                              "operand" : [ {
                                 "name" : "FiveYearSurveillanceRecommendationText",
                                 "type" : "ExpressionRef"
                              }, {
                                 "valueType" : "{urn:hl7-org:elm-types:r1}String",
                                 "value" : "\n\n",
                                 "type" : "Literal"
                              } ]
                           }, {
                              "name" : "J1RecommendationText",
                              "type" : "ExpressionRef"
                           } ]
                        }
                     } ]
                  }
               }, {
                  "when" : {
                     "type" : "And",
                     "operand" : [ {
                        "type" : "Greater",
                        "operand" : [ {
                           "precision" : "Year",
                           "type" : "CalculateAge",
                           "operand" : {
                              "path" : "birthDate.value",
                              "type" : "Property",
                              "source" : {
                                 "name" : "Patient",
                                 "type" : "ExpressionRef"
                              }
                           }
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                           "value" : "65",
                           "type" : "Literal"
                        } ]
                     }, {
                        "type" : "Equal",
                        "operand" : [ {
                           "name" : "TableRecommendation",
                           "type" : "ExpressionRef"
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "5-year follow-up",
                           "type" : "Literal"
                        } ]
                     } ]
                  },
                  "then" : {
                     "type" : "Tuple",
                     "element" : [ {
                        "name" : "action",
                        "value" : {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "Surveillance",
                           "type" : "Literal"
                        }
                     }, {
                        "name" : "text",
                        "value" : {
                           "type" : "Concatenate",
                           "operand" : [ {
                              "type" : "Concatenate",
                              "operand" : [ {
                                 "type" : "Concatenate",
                                 "operand" : [ {
                                    "type" : "Concatenate",
                                    "operand" : [ {
                                       "name" : "FiveYearSurveillanceRecommendationText",
                                       "type" : "ExpressionRef"
                                    }, {
                                       "valueType" : "{urn:hl7-org:elm-types:r1}String",
                                       "value" : "\n\n",
                                       "type" : "Literal"
                                    } ]
                                 }, {
                                    "name" : "J1RecommendationText",
                                    "type" : "ExpressionRef"
                                 } ]
                              }, {
                                 "valueType" : "{urn:hl7-org:elm-types:r1}String",
                                 "value" : "\n\n",
                                 "type" : "Literal"
                              } ]
                           }, {
                              "name" : "Over65RecommendationText",
                              "type" : "ExpressionRef"
                           } ]
                        }
                     } ]
                  }
               }, {
                  "when" : {
                     "type" : "And",
                     "operand" : [ {
                        "type" : "GreaterOrEqual",
                        "operand" : [ {
                           "precision" : "Year",
                           "type" : "CalculateAge",
                           "operand" : {
                              "path" : "birthDate.value",
                              "type" : "Property",
                              "source" : {
                                 "name" : "Patient",
                                 "type" : "ExpressionRef"
                              }
                           }
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                           "value" : "25",
                           "type" : "Literal"
                        } ]
                     }, {
                        "type" : "Equal",
                        "operand" : [ {
                           "name" : "TableRecommendation",
                           "type" : "ExpressionRef"
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "Colposcopy",
                           "type" : "Literal"
                        } ]
                     } ]
                  },
                  "then" : {
                     "type" : "Tuple",
                     "element" : [ {
                        "name" : "action",
                        "value" : {
                           "name" : "TableRecommendation",
                           "type" : "ExpressionRef"
                        }
                     }, {
                        "name" : "text",
                        "value" : {
                           "name" : "ColposcopyRecommendationText",
                           "type" : "ExpressionRef"
                        }
                     } ]
                  }
               }, {
                  "when" : {
                     "type" : "And",
                     "operand" : [ {
                        "type" : "And",
                        "operand" : [ {
                           "type" : "GreaterOrEqual",
                           "operand" : [ {
                              "precision" : "Year",
                              "type" : "CalculateAge",
                              "operand" : {
                                 "path" : "birthDate.value",
                                 "type" : "Property",
                                 "source" : {
                                    "name" : "Patient",
                                    "type" : "ExpressionRef"
                                 }
                              }
                           }, {
                              "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                              "value" : "25",
                              "type" : "Literal"
                           } ]
                        }, {
                           "type" : "LessOrEqual",
                           "operand" : [ {
                              "precision" : "Year",
                              "type" : "CalculateAge",
                              "operand" : {
                                 "path" : "birthDate.value",
                                 "type" : "Property",
                                 "source" : {
                                    "name" : "Patient",
                                    "type" : "ExpressionRef"
                                 }
                              }
                           }, {
                              "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                              "value" : "50",
                              "type" : "Literal"
                           } ]
                        } ]
                     }, {
                        "type" : "Equal",
                        "operand" : [ {
                           "name" : "TableRecommendation",
                           "type" : "ExpressionRef"
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "Colposcopy/Treatment",
                           "type" : "Literal"
                        } ]
                     } ]
                  },
                  "then" : {
                     "type" : "Tuple",
                     "element" : [ {
                        "name" : "action",
                        "value" : {
                           "name" : "TableRecommendation",
                           "type" : "ExpressionRef"
                        }
                     }, {
                        "name" : "text",
                        "value" : {
                           "type" : "Concatenate",
                           "operand" : [ {
                              "type" : "Concatenate",
                              "operand" : [ {
                                 "name" : "ColposcopyOrTreatmentRecommendationText",
                                 "type" : "ExpressionRef"
                              }, {
                                 "valueType" : "{urn:hl7-org:elm-types:r1}String",
                                 "value" : "\n\n",
                                 "type" : "Literal"
                              } ]
                           }, {
                              "name" : "TreatmentWithPregnancyConcernsRecommendationText",
                              "type" : "ExpressionRef"
                           } ]
                        }
                     } ]
                  }
               }, {
                  "when" : {
                     "type" : "And",
                     "operand" : [ {
                        "type" : "Greater",
                        "operand" : [ {
                           "precision" : "Year",
                           "type" : "CalculateAge",
                           "operand" : {
                              "path" : "birthDate.value",
                              "type" : "Property",
                              "source" : {
                                 "name" : "Patient",
                                 "type" : "ExpressionRef"
                              }
                           }
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                           "value" : "50",
                           "type" : "Literal"
                        } ]
                     }, {
                        "type" : "Equal",
                        "operand" : [ {
                           "name" : "TableRecommendation",
                           "type" : "ExpressionRef"
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "Colposcopy/Treatment",
                           "type" : "Literal"
                        } ]
                     } ]
                  },
                  "then" : {
                     "type" : "Tuple",
                     "element" : [ {
                        "name" : "action",
                        "value" : {
                           "name" : "TableRecommendation",
                           "type" : "ExpressionRef"
                        }
                     }, {
                        "name" : "text",
                        "value" : {
                           "name" : "ColposcopyOrTreatmentRecommendationText",
                           "type" : "ExpressionRef"
                        }
                     } ]
                  }
               }, {
                  "when" : {
                     "type" : "And",
                     "operand" : [ {
                        "type" : "And",
                        "operand" : [ {
                           "type" : "GreaterOrEqual",
                           "operand" : [ {
                              "precision" : "Year",
                              "type" : "CalculateAge",
                              "operand" : {
                                 "path" : "birthDate.value",
                                 "type" : "Property",
                                 "source" : {
                                    "name" : "Patient",
                                    "type" : "ExpressionRef"
                                 }
                              }
                           }, {
                              "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                              "value" : "25",
                              "type" : "Literal"
                           } ]
                        }, {
                           "type" : "LessOrEqual",
                           "operand" : [ {
                              "precision" : "Year",
                              "type" : "CalculateAge",
                              "operand" : {
                                 "path" : "birthDate.value",
                                 "type" : "Property",
                                 "source" : {
                                    "name" : "Patient",
                                    "type" : "ExpressionRef"
                                 }
                              }
                           }, {
                              "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                              "value" : "50",
                              "type" : "Literal"
                           } ]
                        } ]
                     }, {
                        "type" : "Equal",
                        "operand" : [ {
                           "name" : "TableRecommendation",
                           "type" : "ExpressionRef"
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "Treatment",
                           "type" : "Literal"
                        } ]
                     } ]
                  },
                  "then" : {
                     "type" : "Tuple",
                     "element" : [ {
                        "name" : "action",
                        "value" : {
                           "name" : "TableRecommendation",
                           "type" : "ExpressionRef"
                        }
                     }, {
                        "name" : "text",
                        "value" : {
                           "type" : "Concatenate",
                           "operand" : [ {
                              "type" : "Concatenate",
                              "operand" : [ {
                                 "name" : "TreatmentRecommendationText",
                                 "type" : "ExpressionRef"
                              }, {
                                 "valueType" : "{urn:hl7-org:elm-types:r1}String",
                                 "value" : "\n\n",
                                 "type" : "Literal"
                              } ]
                           }, {
                              "name" : "TreatmentWithPregnancyConcernsRecommendationText",
                              "type" : "ExpressionRef"
                           } ]
                        }
                     } ]
                  }
               }, {
                  "when" : {
                     "type" : "And",
                     "operand" : [ {
                        "type" : "Greater",
                        "operand" : [ {
                           "precision" : "Year",
                           "type" : "CalculateAge",
                           "operand" : {
                              "path" : "birthDate.value",
                              "type" : "Property",
                              "source" : {
                                 "name" : "Patient",
                                 "type" : "ExpressionRef"
                              }
                           }
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                           "value" : "50",
                           "type" : "Literal"
                        } ]
                     }, {
                        "type" : "Equal",
                        "operand" : [ {
                           "name" : "TableRecommendation",
                           "type" : "ExpressionRef"
                        }, {
                           "valueType" : "{urn:hl7-org:elm-types:r1}String",
                           "value" : "Treatment",
                           "type" : "Literal"
                        } ]
                     } ]
                  },
                  "then" : {
                     "type" : "Tuple",
                     "element" : [ {
                        "name" : "action",
                        "value" : {
                           "name" : "TableRecommendation",
                           "type" : "ExpressionRef"
                        }
                     }, {
                        "name" : "text",
                        "value" : {
                           "name" : "TreatmentRecommendationText",
                           "type" : "ExpressionRef"
                        }
                     } ]
                  }
               } ],
               "else" : {
                  "type" : "As",
                  "operand" : {
                     "type" : "Null"
                  },
                  "asTypeSpecifier" : {
                     "type" : "TupleTypeSpecifier",
                     "element" : [ {
                        "name" : "action",
                        "type" : {
                           "name" : "{urn:hl7-org:elm-types:r1}String",
                           "type" : "NamedTypeSpecifier"
                        }
                     }, {
                        "name" : "text",
                        "type" : {
                           "name" : "{urn:hl7-org:elm-types:r1}String",
                           "type" : "NamedTypeSpecifier"
                        }
                     } ]
                  }
               }
            }
         } ]
      }
   }
}

