id: fhir.us.ccsm
canonical: http://hl7.org/fhir/us/ccsm
name: CervicalCancerScreeningAndManagement
status: draft
version: 0.1.0
fhirVersion: 4.0.1
FSHOnly: true
dependencies:
  hl7.fhir.us.core: 3.1.0
  hl7.fhir.uv.cpg: 1.0.0
  hl7.fhir.uv.sdc: 2.7.0