RuleSet: CPGKnowledgeExtensions
* extension[+].url = "http://hl7.org/fhir/uv/cpg/StructureDefinition/cpg-knowledgeCapability"
* extension[=].valueCode = http://hl7.org/fhir/uv/cpg/CodeSystem/cpg-knowledge-capability#executable "Executable"
* extension[+].url = "http://hl7.org/fhir/uv/cpg/StructureDefinition/cpg-knowledgeRepresentationLevel"
* extension[=].valueCode = http://hl7.org/fhir/uv/cpg/CodeSystem/cpg-knowledge-representation-level#structured "Structured"

RuleSet: CommonMetadata
* version = "1.0.0"
* date = "2021-09-14"
* status = http://hl7.org/fhir/publication-status#draft "Draft"
* experimental = true
* publisher = "The Health FFRDC, operated by The MITRE Corporation, in support of the Division of Cancer Prevention and Control, Centers for Disease Control and Prevention."
* copyright = "(C) 2021 The MITRE Corporation. All Rights Reserved. Approved for Public Release: 21-1556. Distribution Unlimited. Unless otherwise noted, this work is available under an Apache 2.0 license. It was produced by the MITRE Corporation for the Division of Cancer Prevention and Control, Centers for Disease Control and Prevention in accordance with the Statement of Work, contract number 75FCMC18D0047, task order number 75D30120F09743."
* approvalDate = "2021-09-14"
* lastReviewDate = "2021-09-14"
* author[+].name = "The Health FFRDC, operated by The MITRE Corporation, in support of the Division of Cancer Prevention and Control, Centers for Disease Control and Prevention."
* editor[+].name = "Division of Cancer Prevention and Control, Centers for Disease Control and Prevention"
* reviewer[+].name = "Division of Cancer Prevention and Control, Centers for Disease Control and Prevention"
* endorser[+].name = "Division of Cancer Prevention and Control, Centers for Disease Control and Prevention"

RuleSet: ManagementCitationActionDocumentation
* action[=].documentation[+].type = $RATYPE#citation "Citation"
* action[=].documentation[=].label = "Management"
* action[=].documentation[=].display = "2019 ASCCP Risk-Based Management Consensus Guidelines for Abnormal Cervical Cancer Screening Tests and Cancer Precursors"
* action[=].documentation[=].citation = "Perkins, Rebecca B. MD, MSc; Guido, Richard S. MD; Castle, Philip E. PhD; Chelmow, David MD; Einstein, Mark H. MD, MS; Garcia, Francisco MD, MPH; Huh, Warner K. MD; Kim, Jane J. PhD, MSc; Moscicki, Anna-Barbara MD; Nayar, Ritu MD; Saraiya, Mona MD, MPH; Sawaya, George F. MD; Wentzensen, Nicolas MD, PhD, MS; Schiffman, Mark MD, MPH; for the 2019 ASCCP Risk-Based Management Consensus Guidelines Committee. 2019 ASCCP Risk-Based Management Consensus Guidelines for Abnormal Cervical Cancer Screening Tests and Cancer Precursors. Journal of Lower Genital Tract Disease 24(2):p 102-131, April 2020. | DOI: 10.1097/LGT.0000000000000525"
* action[=].documentation[=].url = "https://www.asccp.org/management-guidelines"

RuleSet: ManagementCitationActionActionDocumentation
* action[=].action[=].documentation[+].type = $RATYPE#citation "Citation"
* action[=].action[=].documentation[=].label = "Management"
* action[=].action[=].documentation[=].display = "2019 ASCCP Risk-Based Management Consensus Guidelines for Abnormal Cervical Cancer Screening Tests and Cancer Precursors"
* action[=].action[=].documentation[=].citation = "Perkins, Rebecca B. MD, MSc; Guido, Richard S. MD; Castle, Philip E. PhD; Chelmow, David MD; Einstein, Mark H. MD, MS; Garcia, Francisco MD, MPH; Huh, Warner K. MD; Kim, Jane J. PhD, MSc; Moscicki, Anna-Barbara MD; Nayar, Ritu MD; Saraiya, Mona MD, MPH; Sawaya, George F. MD; Wentzensen, Nicolas MD, PhD, MS; Schiffman, Mark MD, MPH; for the 2019 ASCCP Risk-Based Management Consensus Guidelines Committee. 2019 ASCCP Risk-Based Management Consensus Guidelines for Abnormal Cervical Cancer Screening Tests and Cancer Precursors. Journal of Lower Genital Tract Disease 24(2):p 102-131, April 2020. | DOI: 10.1097/LGT.0000000000000525"
* action[=].action[=].documentation[=].url = "https://www.asccp.org/management-guidelines"

RuleSet: ScreeningCitationActionDocumentation
* action[=].documentation[+].type = $RATYPE#citation "Citation"
* action[=].documentation[=].label = "Screening: Average Risk"
* action[=].documentation[=].display = "2018 USPSTF Cervical Cancer Screening Recommendations"
* action[=].documentation[=].citation = "United States Preventive Services Task Force, \"Final Recommendation Statement: Cervical Cancer Screening,\" 21 August 2018."
* action[=].documentation[=].url = "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/cervical-cancer-screening"
* action[=].documentation[+].type = $RATYPE#citation "Citation"
* action[=].documentation[=].label = "Screening: Symptomatic"
* action[=].documentation[=].display = "Evaluation of the Cervix in Patients with Abnormal Vaginal Bleeding"
* action[=].documentation[=].citation = "ASCCP Clinical Practice Statement, \"Evaluation of the Cervix in Patients with Abnormal Vaginal Bleeding,\" 7 February 2017."
* action[=].documentation[=].url = "https://www.asccp.org/Assets/9d92e617-858f-43f3-af62-44adf76cfc67/636220616039000000/vaginal-bleeding-statement-final-02-06-17-pdf"
* action[=].documentation[+].type = $RATYPE#citation "Citation"
* action[=].documentation[=].label = "Screening: DES Exposure"
* action[=].documentation[=].display = "Practice Bulletin No. 168: Cervical Cancer Screening and Prevention"
* action[=].documentation[=].citation = "\"Practice Bulletin No. 168: Cervical Cancer Screening and Prevention,\" Obstetrics and Gynecology, vol. 1284, no. 4, pp. e111-e130, 2016."
* action[=].documentation[=].url = "https://pubmed.ncbi.nlm.nih.gov/27661651/"
* action[=].documentation[+].type = $RATYPE#citation "Citation"
* action[=].documentation[=].label = "Screening: DES Exposure"
* action[=].documentation[=].display = "Antenatal exposure to DES: Lessons Learned...Future Concerns"
* action[=].documentation[=].citation = "M. Rubin, \"Antenatal exposure to DES: Lessons Learned...Future Concerns,\" Obstetrical & Gynecological Survey, vol. 62, no. 8, pp. 548-555, 2007."
* action[=].documentation[=].url = "https://pubmed.ncbi.nlm.nih.gov/17634156/"
* action[=].documentation[+].type = $RATYPE#citation "Citation"
* action[=].documentation[=].label = "Screening: Immunocompromised"
* action[=].documentation[=].display = "Guidelines for the prevention and treatment of opportunistic infections in adults and adolescents with HIV"
* action[=].documentation[=].citation = "Panel on Opportunistic Infections in Adults and Adolescents with HIV, \"Guidelines for the prevention and treatment of opportunistic infections in adults and adolescents with HIV: Recommendations from the CDC, the NIH, and the HIV Medicine Association of the Infectious Diseases Society of America,\" 29 November 2018."
* action[=].documentation[=].url = "https://clinicalinfo.hiv.gov/en/guidelines/adult-and-adolescent-opportunistic-infection/human-papillomavirus-disease"
* action[=].documentation[+].type = $RATYPE#citation "Citation"
* action[=].documentation[=].label = "Screening: Immunocompromised"
* action[=].documentation[=].display = "Guidelines for Cervical Cancer Screening in Immunosuppressed Women Without HIV Infection"
* action[=].documentation[=].citation = "A.-B. Moscicki, L. Flowers, M. J. Huchko, M. E. Long, K. L. MacLaughlin, J. Murphy, L. B. Spiryda and M. A. Gold, \"Guidelines for Cervical Cancer Screening in Immunosuppressed Women Without HIV Infection,\" Journal of Lower Genital Tract Disease, vol. 23, no. 2, pp. 87-101, 2019."
* action[=].documentation[=].url = "https://pubmed.ncbi.nlm.nih.gov/30907775/"

RuleSet: ScreeningCitationActionActionDocumentation
* action[=].action[=].documentation[+].type = $RATYPE#citation "Citation"
* action[=].action[=].documentation[=].label = "Screening: Average Risk"
* action[=].action[=].documentation[=].display = "2018 USPSTF Cervical Cancer Screening Recommendations"
* action[=].action[=].documentation[=].citation = "United States Preventive Services Task Force, \"Final Recommendation Statement: Cervical Cancer Screening,\" 21 August 2018."
* action[=].action[=].documentation[=].url = "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/cervical-cancer-screening"
* action[=].action[=].documentation[+].type = $RATYPE#citation "Citation"
* action[=].action[=].documentation[=].label = "Screening: Symptomatic"
* action[=].action[=].documentation[=].display = "Evaluation of the Cervix in Patients with Abnormal Vaginal Bleeding"
* action[=].action[=].documentation[=].citation = "ASCCP Clinical Practice Statement, \"Evaluation of the Cervix in Patients with Abnormal Vaginal Bleeding,\" 7 February 2017."
* action[=].action[=].documentation[=].url = "https://www.asccp.org/Assets/9d92e617-858f-43f3-af62-44adf76cfc67/636220616039000000/vaginal-bleeding-statement-final-02-06-17-pdf"
* action[=].action[=].documentation[+].type = $RATYPE#citation "Citation"
* action[=].action[=].documentation[=].label = "Screening: DES Exposure"
* action[=].action[=].documentation[=].display = "Practice Bulletin No. 168: Cervical Cancer Screening and Prevention"
* action[=].action[=].documentation[=].citation = "\"Practice Bulletin No. 168: Cervical Cancer Screening and Prevention,\" Obstetrics and Gynecology, vol. 1284, no. 4, pp. e111-e130, 2016."
* action[=].action[=].documentation[=].url = "https://pubmed.ncbi.nlm.nih.gov/27661651/"
* action[=].action[=].documentation[+].type = $RATYPE#citation "Citation"
* action[=].action[=].documentation[=].label = "Screening: DES Exposure"
* action[=].action[=].documentation[=].display = "Antenatal exposure to DES: Lessons Learned...Future Concerns"
* action[=].action[=].documentation[=].citation = "M. Rubin, \"Antenatal exposure to DES: Lessons Learned...Future Concerns,\" Obstetrical & Gynecological Survey, vol. 62, no. 8, pp. 548-555, 2007."
* action[=].action[=].documentation[=].url = "https://pubmed.ncbi.nlm.nih.gov/17634156/"
* action[=].action[=].documentation[+].type = $RATYPE#citation "Citation"
* action[=].action[=].documentation[=].label = "Screening: Immunocompromised"
* action[=].action[=].documentation[=].display = "Guidelines for the prevention and treatment of opportunistic infections in adults and adolescents with HIV"
* action[=].action[=].documentation[=].citation = "Panel on Opportunistic Infections in Adults and Adolescents with HIV, \"Guidelines for the prevention and treatment of opportunistic infections in adults and adolescents with HIV: Recommendations from the CDC, the NIH, and the HIV Medicine Association of the Infectious Diseases Society of America,\" 29 November 2018."
* action[=].action[=].documentation[=].url = "https://clinicalinfo.hiv.gov/en/guidelines/adult-and-adolescent-opportunistic-infection/human-papillomavirus-disease"
* action[=].action[=].documentation[+].type = $RATYPE#citation "Citation"
* action[=].action[=].documentation[=].label = "Screening: Immunocompromised"
* action[=].action[=].documentation[=].display = "Guidelines for Cervical Cancer Screening in Immunosuppressed Women Without HIV Infection"
* action[=].action[=].documentation[=].citation = "A.-B. Moscicki, L. Flowers, M. J. Huchko, M. E. Long, K. L. MacLaughlin, J. Murphy, L. B. Spiryda and M. A. Gold, \"Guidelines for Cervical Cancer Screening in Immunosuppressed Women Without HIV Infection,\" Journal of Lower Genital Tract Disease, vol. 23, no. 2, pp. 87-101, 2019."
* action[=].action[=].documentation[=].url = "https://pubmed.ncbi.nlm.nih.gov/30907775/"